---

name: linters

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout-action
        uses: actions/checkout@v3
      - name: dprint-check-action
        uses: dprint/check@v2.1
